version: "3.8"
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot-app
    depends_on:
      - mysql-db
    ports:
      - "2005:2005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mongo-db:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask-app:
    build: ./flask-app
    container_name: flask-app
    depends_on:
      - mongo-db
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo-db:27017/mydb

volumes:
  mysql_data:
  mongo_data: